config/routes.rb
Rails.application.routes.draw do
  root to: 'tweets#index'

  resources :tweets
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  validates :tweet_text, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  def index
    sleep 1
    @tweets = Tweet.all
  end

  def show

  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    if @tweet.save
      # flash[:notice] = "Tweet successfully added!"
      respond_to do |format|
        format.html { redirect_to tweets_path }
        format.js { flash.now[:notice] = "Tweet successfully added!" }
      end
    else
      respond_to do |format|
        format.html { render :new }
        format.js { flash.now[:alert] = "Error in new tweet entry. Try again." }
      end
    end
  end

  def destroy
    @tweet = Tweet.find(params[:id]).destroy()
    respond_to do |format|
      format.html { redirect_to tweets_path }
      format.js { flash.now[:notice] = "Tweet successfully deleted!" }
    end
  end

  private
    def tweet_params
      params.require(:tweet).permit(:tweet_text)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_notices.html.erb
<div data-alert class="alert-box">
  <%= notice %>
  <%= alert %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitter Clone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class='container'>

    <div id='flash'>
      <% if notice.present? %>
        <%= render 'notices' %>
      <% end %>
    </div>

    <%= yield %>
  </div>
</body>
</html>

app/views/tweets/_form.html.erb
<%= form_for @tweet, remote: true do |f| %>
  <div class='form-group'>
    <%= f.label :tweet_text %>
    <%= f.text_field :tweet_text, class: 'form-control' %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/tweets/_tweet.html.erb
<%= form_for tweet do |f| %>
  <%= f.label :complete, tweet.tweet_text %>
  <%= link_to "(remove)", tweet, method: :delete,
    data: {confirm: "Are you sure?"}, remote: true, class:'delete_things' %>
<% end %>

app/views/tweets/create.js.erb
$('#new_tweet').remove();
$('#new_tweet_link').show();
$('#current_tweets').append('<%= j render(@tweet) %>');

$('#flash').html('<%= j render "layouts/notices" %>');

app/views/tweets/destroy.js.erb
$('#edit_tweet_<%= @tweet.id %>').remove();

$('#flash').html('<%= j render "layouts/notices" %>');

app/views/tweets/index.html.erb
<h3>Tweets:</h3>

<%= link_to "New Tweet", new_tweet_path,
  id: "new_tweet_link", remote: true %>

<ul id="current_tweets">
  <%= render @tweets %>
</ul>

app/views/tweets/new.js.erb
$('#new_tweet_link').hide().after('<%= j render("form") %>');